// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = " ";   //Enter your DEVICE_ID From Arduino Cloud

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBlindsChange();
void onAirConChange();
void onFanChange();
void onThermostatChange();

CloudDimmedLight blinds;
CloudSwitch airCon;
CloudSwitch fan;
CloudTemperatureSensor temperature;
CloudTemperatureSensor thermostat;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(blinds, READWRITE, ON_CHANGE, onBlindsChange);
  ArduinoCloud.addProperty(airCon, READWRITE, ON_CHANGE, onAirConChange);
  ArduinoCloud.addProperty(fan, READWRITE, ON_CHANGE, onFanChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(thermostat, READWRITE, ON_CHANGE, onThermostatChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
